
default: help
.PHONY: default

status:
	@echo show status
.PHONY: status

deploy:
	@echo deploying...
.PHONY: deploy

help:
	@echo make [command]
	@echo ====================
	@echo make help
	@echo make status
	@echo make deploy
.PHONY: help
