
.PHONY: default help status deploy

default: help

status:
	@echo show status

deploy:
	@echo deploying...

help:
	@echo make [command]
	@echo ====================
	@echo make help
	@echo make status
	@echo make deploy
